safety_config:
  early_stopping: true

input_detectors:
  - name: "SimpleDetector1_input"
    class_path: "safeguard_llm.detectors.simple_detector.SimpleDetector"
    args: null
    
  - name: "SimpleDetector43_input"
    class_path: "safeguard_llm.detectors.simple_detector.SimpleDetector"
    args: null

  - name: "SimpleDetector3_input"
    class_path: "safeguard_llm.detectors.simple_detector.SimpleDetector"
    args: null


internal_detectors: 
  - name: "LPInternalDetector1"
    class_path: "safeguard_llm.detectors.internal.linear_probe_detector.LinearProbeDetector"
    args: 
      model_path: "src/safeguard_llm/models/linear_probe/model_linear_toxicity_qwen3_1_7b_l27_res_stream.pt"      
      device: "cuda"
      target_layer_name: model.layers.27
      input_eval_only: True
      threshold: 0.5

output_detectors:
  - name: "SimpleDetector1_input"
    class_path: "safeguard_llm.detectors.simple_detector.SimpleDetector"
    args: null
    
  - name: "SimpleDetector2_input"
    class_path: "safeguard_llm.detectors.simple_detector.SimpleDetector"
    args: null

  - name: "SimpleDetector3_input"
    class_path: "safeguard_llm.detectors.simple_detector.SimpleDetector"
    args: null



