_defaults:
  device: &device "cuda"

input_detectors:
  - name: "InputDetector1"
    class_path: safeguard_llm.detectors.bert_detector.BERTdetector
    args: 
      model_path: "bert_models/roberta-input-classifier-jb/checkpoint-8120"    
      device: *device
      threshold: 0.95
      label_pos: 1

internal_detectors: 
  - name: "InternalDetector1"
    class_path: "safeguard_llm.detectors.internal.linear_probe_detector.LinearProbeDetector"
    args: 
      model_path: "src/safeguard_llm/models/linear_probe/model_linear_jailbreak_qwen3_1_7b_res_layer27_simple_jackhhao_jailbreakclassification_template.pt"      
      device: *device
      target_layer_name: model.layers.27
      input_eval_only: True
      threshold: 0.95

output_detectors:
  - name: "OutputDetector1"
    class_path: safeguard_llm.detectors.bert_detector.BERTdetector
    args: 
      model_path: "bert_models/roberta_harm_aug/checkpoint-12297"    
      device: *device
      threshold: 0.5
      label_pos: 1



