_defaults:
  device: &device "cuda"

input_detectors:
  - name: "JackhaoBertJBClassifier"
    class_path: "safeguard_llm.detectors.bert_detector.BERTdetector"
    args: 
      model_path: "jackhhao/jailbreak-classifier"      
      device: *device
      threshold: 0.5


internal_detectors: 
  - name: "LPInternalDetector1"
    class_path: "safeguard_llm.detectors.internal.linear_probe_detector.LinearProbeDetector"
    args: 
      model_path: "src/safeguard_llm/models/linear_probe/model_linear_jailbreak_qwen3_1_7b_res_layer27_simple_jackhhao_jailbreakclassification.pt"      
      device: *device
      target_layer_name: model.layers.27
      input_eval_only: True
      threshold: 0.5

output_detectors:
  - name: "SimpleDetector1_input"
    class_path: "safeguard_llm.detectors.simple_detector.SimpleDetector"
    args: null
    



