import time
from typing import Callable, Any, Optional
import uuid
from dataclasses import dataclass, field

from transformers import AutoTokenizer

from safeguard_llm.detectors.detector import Detector
from safeguard_llm.detectors.internal.internal_detector import InternalDetector
from pathlib import Path 
from safeguard_llm.utils.load_config import load_safety_config
from safeguard_llm.utils.classification_rules import classify_any_or_rule
#for one prompt, we want to allow multiple safety mechanisms 
@dataclass
class GenerationSafetyResult:
    """ Results storage class for safety evaluations and single LLM generations

    Attributes:
        prompt: Input prompt to the model
        output: The response generated by the model.
        input_disapprovals: Links input detectors to their results such as latency, classification
        internal_disapprovals: Links internal detectors to their results such as latency, classif
        output_disapprovals: Links output detectors to their results such as latency, classif
        id: uuid identifier for this results entry
        overall_disapproval: Ensemble classification
        prompt_label_gold: Ground truth for the input prompt
        output_label_gold: Ground truth for the output prompt
    """
    prompt: str 
    output: str
    # map detector_name -> {"class_name": str, "approved": bool}
    input_disapprovals: dict[str, dict[str, Any]]
    internal_disapprovals: dict[str, dict[str, Any]]
    output_disapprovals: dict[str, dict[str, Any]]
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    overall_disapproval: bool = True
    prompt_label_gold: Optional[int] = None
    output_label_gold: Optional[int] = None  



class SafeLLM():
    """A safety-wrapped LLM pipeline incorporating input, internal and output detectors as guardrails

    Attributes:
        model: The LLM instance for text generation
        tokenizer: Tokenizer for the corresponding model
        max_gen_len: Maximum allowed token generation
        input_detectors: Detectors evaluating the input prompts
        internal_detectors: Detectors monitoring the internal activations
        output_detectors: Detectors evaluating the model output
        safety_config: Entails the Safety Harness configuration to deploy around the LLM
        forward_hooks: Active hooks of internal detectors
        classification_rule: Function determining the ensemble strategy for the LLM Safety Harness
    """
    #default to any rule
    def __init__(self, model: Any, tokenizer: AutoTokenizer, max_gen_len: int, config_path: Path, classification_rule:Callable = classify_any_or_rule):
        """ Initialize safety detectors, tokenizer config and linear probe hooks

        Args:
            model: Language model for text generation
            tokenizer: Corresponding tokenizer
            max_gen_len: Max generation length
            config_path: Path to yaml safety config
            classification_rule: Ensemble rule for the Safety Harness. Defaults to "classify_any_or_rule"

        """
        config = load_safety_config(config_path)
        self.input_detectors: list[tuple[Detector, str]] = config["input_detectors"]  
        self.internal_detectors: list[tuple[InternalDetector, str]] = config["internal_detectors"] 
        self.output_detectors: list[tuple[Detector, str]] = config["output_detectors"] 
        self.safety_config: dict[str, Any] = config["safety_config"]
        self.forward_hooks = []
        self.model = model
        self.tokenizer = tokenizer
        self.max_gen_len = max_gen_len
        #set the overall disapproval
        self.classification_rule = classification_rule
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
            self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
        self.tokenizer.padding_side = "left"
        if self.internal_detectors:
            self.apply_internal_detectors(self.internal_detectors)

    def apply_io_detectors(self, elements: list[str], detectors: list[tuple[Detector, str]]) -> list[dict[str, bool]]:
        """ Perform input/output text detectors on the input strings

        Args:
            elements: Batch of text prompts or model generations to classify
            detectors: Detector model to apply

        Returns:
            List of evaluation metrics including detector name, classification result and inference latency
        """
        input_disapprovals = [{} for _ in elements]
        for detector_instance, detector_name in detectors:
            start_time = time.perf_counter()
            input_disapproval_per_batch: list[bool] = detector_instance.is_unsafe(elements)
            latency = (time.perf_counter() - start_time) * 1000 # convert into ms
            for i, disapproval in enumerate(input_disapproval_per_batch): 
                input_disapprovals[i][detector_name] = {
                    "class_name": detector_instance.__class__.__name__,
                    "disapproved": disapproval,
                    "latency": round(latency, 2)
                }
        return input_disapprovals 

    #register hooks for the model
    def apply_internal_detectors(self, detectors: list[tuple[InternalDetector, str]]) -> None: 
        """ Register hook for internal detector

        Args:
            detectors: list of internal detectors

        """
        for detector_instance, _ in detectors:
                layer = detector_instance.target_layer
                submodule = self.model.get_submodule(layer)
                self.forward_hooks.append(submodule.register_forward_hook(detector_instance.hook))

    def remove_internal_detectors(self) -> None:
        """ Remove and unregister hook"""
        for fwd_hook in self.forward_hooks: 
            fwd_hook.remove()
        self.forward_hooks.clear()  
        
    def _generate(self,inputs: list[str]) -> tuple[list[str],list[dict[str, bool]]]:
        """ Tokenizes the inputs, generates a model respone and applies internal linear probe monitoring.

        Args:
            inputs: Raw input prompt strings.

        Returns:
            - Decoded text generations from the model
            - Internal detector classifications
        """
        internal_disapprovals = [{} for _ in inputs]
        for internal_detector, _ in self.internal_detectors:
            internal_detector.disapprovals = []
        messages = [
            [{"role": "user", "content": prompt}]
            for prompt in inputs
        ]
        prompts = self.tokenizer.apply_chat_template(
            messages, 
            tokenize=False, 
            add_generation_prompt=True,
            enable_thinking=False
        )
        tokenized = self.tokenizer(prompts, return_tensors ="pt", padding=True, truncation=True).to(self.model.device)
        input_len = tokenized["input_ids"].shape[1]
        outputs = self.model.generate(**tokenized, max_new_tokens = self.max_gen_len)
        outputs = outputs[:,input_len:]
        #read from hooks 
        for internal_detector, detector_name in self.internal_detectors:
                    start_time = time.perf_counter()
                    internal_disapproval_per_batch = internal_detector.is_unsafe()
                    latency = (time.perf_counter() - start_time) * 1000 # convert into ms
                    for i, disapproval in enumerate(internal_disapproval_per_batch): 
                        internal_disapprovals[i][detector_name] = {
                            "class_name": internal_detector.__class__.__name__,
                            "disapproved": disapproval,
                            "latency": latency
                        }
        return self.tokenizer.batch_decode(outputs, skip_special_tokens=True), internal_disapprovals

    #allow for batched input
    def generate(self, inputs: list[str]) -> list[GenerationSafetyResult]:
        """ Generates responses for batched inputs for the pipeline

        Executes input detection, internal detection in the layers and output detection after generation
        aggregating the results and applying the ensemble classification rule

        Args:
            inputs: Prompt strings to process

        Returns:
            Evaluation details and safety classification results for each prompt in the list
        """
        safety_result_list = []
        input_disapprovals_batch = [{} for _ in range(len(inputs))]
        output_disapprovals_batch = [{} for _ in range(len(inputs))]
        for internal_detector, _ in self.internal_detectors:
                internal_detector.reset()
        if self.input_detectors:
            input_disapprovals_batch = self.apply_io_detectors(inputs,detectors = self.input_detectors) 
        outputs, internal_disapprovals_batch = self._generate(inputs)
        if self.output_detectors:
            output_disapprovals_batch = self.apply_io_detectors(outputs,detectors = self.output_detectors) 
        for i, input in enumerate(inputs): 
            overall_disapproval = self.classification_rule(input_disapprovals_batch[i].values(),internal_disapprovals_batch[i].values(),output_disapprovals_batch[i].values())
            safety_result_list.append(GenerationSafetyResult(
                prompt=input, 
                output=outputs[i], 
                input_disapprovals=input_disapprovals_batch[i], 
                internal_disapprovals=internal_disapprovals_batch[i], 
                output_disapprovals=output_disapprovals_batch[i], 
                overall_disapproval=overall_disapproval
            )) 
        return safety_result_list
 